### ISSUE TITLE
Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by shichunlei** [solid-software/flutter_vlc_player#121]
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 3.6)

we play the video list and click one by one ,after click 4~5 times, the app crash .and print the memory issue

020-10-14 18:20:38.035395+0800 Runner[567:94139] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel flutter_video_plugin/getVideoView_5)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      VlcPlayerController.dispose (package:flutter_vlc_player/flutter_vlc_player.dart:721:26)
#3      _VideoPlayerPageState.dispose (package:educationCommon/src/function/video/video_player_page.dart:87:17)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1998:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#22     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6218:16)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)

#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#73     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#82     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6105:14)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1996:7)
#91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1994:13)
#93     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#94     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2007:25)
#95     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2821:27)
#96     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2621:15)
#97     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2820:7)
#98     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:915:18)
#99     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#100    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#101    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#102    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#103    _rootRun (dart:async/zone.dart:1190:13)
#104    _CustomZone.run (dart:async/zone.dart:1093:19)
#105    _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#106    _invoke (dart:ui/hooks.dart:251:10)
#107    _drawFrame (dart:ui/hooks.dart:209:3)
2020-10-14 18:20:39.615575+0800 Runner[567:93950] creating player instance using shared library
2020

**Comment by rocboronat** [comment]
This PR mentioned all PRs and issues 😂
