### ISSUE TITLE
controler throw erro

### ISSUE THREAD

**Issue by hu70258tao** [solid-software/flutter_vlc_player#220]
i click a fullscreen button,use a inited control like 
![image](https://user-images.githubusercontent.com/20218008/113264679-d0ac3b80-9305-11eb-8895-8f1ce2d31fa2.png)
but it is read 
![image](https://user-images.githubusercontent.com/20218008/113264746-e588cf00-9305-11eb-80a0-eae0269e4a13.png)

**Comment by alr2413** [comment]
You can comment that lines of library to see if the problem goes away or not.

**Comment by hu70258tao** [comment]
and this player is always buffering
![image](https://user-images.githubusercontent.com/20218008/113369426-e7996f00-9393-11eb-9460-6e390b6f49be.png)
like this

**Comment by jing-pei** [comment]
same issues

**Comment by alr2413** [comment]
how did you implement the fullscreen feature?
it's a bit tricky, that's why we didn't implement that in example app.

**Comment by KingTomm** [comment]
the same problem
anyone has solve it :( /cry
E/flutter ( 5866): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Already Initialized
E/flutter ( 5866): #0      VlcPlayerController.initialize (package:flutter_vlc_player/src/vlc_player_controller.dart:176:7)
E/flutter ( 5866): #1      VlcPlayerController.onPlatformViewCreated (package:flutter_vlc_player/src/vlc_player_controller.dart:941:13)

**Comment by LiangHuangBC** [comment]
Same issue, if comment out throw Exception("Already Initialized") , problem solved. Why throw Exception here, will it be removed on next version?
