### ISSUE TITLE
Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: flutter_video_plugin/getVideoView

### ISSUE THREAD

**Issue by arjunkn** [solid-software/flutter_vlc_player#258]
Hi,
I am getting this error when trying to initialize VLC Player launch from URL on a real device. It's working if launch normally, and emulator launch either way.

version: flutter_vlc_player: ^6.0.4

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.60.0)
[✓] Connected device (3 available)
`

**my log**

`
E/flutter (14744): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: flutter_video_plugin/getVideoView
E/flutter (14744): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:197)
E/flutter (14744): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/flutter (14744): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (14744): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (14744): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (14744): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (14744): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14744): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (14744): 	at android.os.Looper.loop(Looper.java:206)
E/flutter (14744): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (14744): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14744): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (14744): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (14744): , null, null)
E/flutter (14744): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (14744): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (14744): <asynchronous suspension>
E/flutter (14744): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1066:18)
E/flutter (14744): <asynchronous suspension>
E/flutter (14744): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:771:5)
E/flutter (14744): <asynchronous suspension>
E/flutter (14744): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
E/flutter (14744): <asynchronous suspension>
E/flutter (14744): `

This issue shows only if launch app from a URL on a real device.

**Comment by faisal-alajmi** [comment]
Im using flutter_vlc_player 7.1.5 and also getting the same error on a real device

[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'flutter_video_plugin/getVideoView', null)

**Comment by gabrielsolomon** [comment]
> Im using flutter_vlc_player 7.1.5 and also getting the same error on a real device
> 
> [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'flutter_video_plugin/getVideoView', null)

Same here. I am using a real device and local file
