### ISSUE TITLE
crash -after using back button in android8.1 when playing RTSP stream

### ISSUE THREAD

**Issue by James-NJCN** [solid-software/flutter_vlc_player#264]
E/flutter ( 7324): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1066:18)
E/flutter ( 7324): <asynchronous suspension>
E/flutter ( 7324): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:771:5)
E/flutter ( 7324): <asynchronous suspension>
E/flutter ( 7324): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
E/flutter ( 7324): <asynchronous suspension>

**Comment by Rukkaitto** [comment]
Same issue on Android 12

**Comment by mitchross** [comment]
@James-NJCN  what are your repo steps?

**Comment by James-NJCN** [comment]
I've just run this in android studio (aka debug mode) with my android phone. @mitchross

**Comment by mitchross** [comment]
Theres no back button functionality in the example app. The back button will just close the sample app, so I'm curious how you are testing and reproducing this.

**Comment by James-NJCN** [comment]
@mitchross  Use andriod back button on bottom of screen,not app's button

**Comment by mitchross** [comment]
@James-NJCN  I understand, but there's no pop functionality. There's no view hierarchy in the sample app that would warrant a back button pop. If you have a sample app that you are having issues with, I'm happy to take a look but unfortunately, I don't think I can help purely based on the example app and I am unable to reproduce without detailed steps as I don't understand where you are trying to navigate back from and to.
