### ISSUE TITLE
RTMP Issue in debug and release mode, BUT ok in Emulator.

### ISSUE THREAD

**Issue by arslanahmadpk** [solid-software/flutter_vlc_player#280]
I am facing an issue that might be because of some of my mistakes. I am playing RTMP link in vlc player it's playing fine in the emulator but crashing the app in the debug or release in the mobile. Following is the Errors, Please guide

Metadata value: none
I/art     (24273): Rejecting re-init on previously-failed class java.lang.Class<software.solid.fluttervlcplayer.-$$Lambda$FlutterVlcPlayer$iNXqoCGYLpbNLrcEiwVj76XncDI>
I/art     (24273): Rejecting re-init on previously-failed class java.lang.Class<software.solid.fluttervlcplayer.-$$Lambda$FlutterVlcPlayer$iNXqoCGYLpbNLrcEiwVj76XncDI>
D/ViewRootImpl(24273): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{8df08c V.E...... R.....I. 0,0-0,0}
D/ViewRootImpl(24273): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
E/VLC     (24273): [b9237688/5ed1] libvlc audio output: GetStaticFieldID(AudioFormat.ENCODING_IEC61937) failed
E/VLC     (24273): [b9237688/5ed1] libvlc audio output: GetStaticFieldID(AudioFormat.ENCODING_DOLBY_TRUEHD) failed
E/VLC     (24273): [b9237688/5ed1] libvlc audio output: FindClass(android/media/audiofx/DynamicsProcessing) failed
I/art     (24273): Rejecting re-init on previously-failed class java.lang.Class<software.solid.fluttervlcplayer.-$$Lambda$FlutterVlcPlayer$iNXqoCGYLpbNLrcEiwVj76XncDI>
E/flutter (24273): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(NoClassDefFoundError, java.lang.NoClassDefFoundError: software.solid.fluttervlcplayer.-$$Lambda$FlutterVlcPlayer$iNXqoCGYLpbNLrcEiwVj76XncDI, null, null)
E/flutter (24273): #0      VlcPlayerApi.create (package:flutter_vlc_player_platform_interface/src/messages/messages.dart:610:7)
E/flutter (24273): <asynchronous suspension>
E/flutter (24273): #1      MethodChannelVlcPlayer.create (package:flutter_vlc_player_platform_interface/src/method_channel/method_channel_vlc_player.dart:55:12)
E/flutter (24273): <asynchronous suspension>
E/flutter (24273): #2      VlcPlayerController.initialize (package:flutter_vlc_player/src/vlc_player_controller.dart:182:5)
E/flutter (24273): <asynchronous suspension>
E/flutter (24273): #3      VlcPlayerController.onPlatformViewCreated (package:flutter_vlc_player/src/vlc_player_controller.dart:941:7)
E/flutter (24273): <asynchronous suspension>
E/flutter (24273):
D/ViewRootImpl(24273): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(24273): ViewPostImeInputStage processPointer 1

**Comment by andrewcapatina** [comment]
@arslanahmadpk 

any update? Currently facing same problem with rtsp and could use some guidance.

Initial thought is it is compilation issue. Emulator fine for me as well. 

Thanks.

**Comment by arslanahmadpk** [comment]
No, I have tried many things. But sadly didn't work out for me I am not blaming vlc maybe I was doing something wrong however after tons of searches added a new player **_fijkplayer_** which is working fine for me.
Having said that VLC is still a great player.

**Comment by andrewcapatina** [comment]
@arslanahmadpk 

I tried making a new project with only dependency being vlc player. I still got the same issue running on hardware. I also followed the installation guide and added necessary files within /android/. 

I tried fijkplayer in the past but I cannot even connect to my server. Not sure why yet. I'm trying fijk today and can play http sources, but am struggling with rtsp. I think both players are great, I like VLCs customizability in regards to adding play/pause/seekbar widgets.

**Comment by wavesnet** [comment]
@arslanahmadpk Sir, can you share android manifest file?
