### ISSUE TITLE
Exception: stopRendererScanning() was called on an uninitialized VlcPlayerController.

### ISSUE THREAD

**Issue by Arialena** [solid-software/flutter_vlc_player#281]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: stopRendererScanning() was called on an uninitialized VlcPlayerController.
E/flutter (21694): #0      VlcPlayerController._throwIfNotInitialized (package:flutter_vlc_player/src/vlc_player_controller.dart:923:7)
E/flutter (21694): #1      VlcPlayerController.stopRendererScanning (package:flutter_vlc_player/src/vlc_player_controller.dart:887:5)
E/flutter (21694): #2      ArticleDetailsPageState.dispose (package:jytc_baby/page/home/article_detailed_page.dart:930:20)
E/flutter (21694): #3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4895:11)
E/flutter (21694): #4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
E/flutter (21694): #5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
E/flutter (21694): #7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
E/flutter (21694): #10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
E/flutter (21694): #13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
E/flutter (21694): #16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
E/flutter (21694): #19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
E/flutter (21694): #22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
E/flutter (21694): #25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #27     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
E/flutter (21694): #28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
E/flutter (21694): #31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #33     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
E/flutter (21694): #34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
E/flutter (21694): #37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
E/flutter (21694): #38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
E/flutter (21694): #39     ComponentElement.visitChildren (package:f

**Comment by cogesum** [comment]
any updates?
