### ISSUE TITLE
App Crashes On Build - Can't load vlcjni library

### ISSUE THREAD

**Issue by This-Is-Not-Brad** [solid-software/flutter_vlc_player#351]
When building and running the app in release mode I get the following error when I try to open a page with the VLC Player Controller:

```
2022-07-26 17:59:13.258 17311-17311/? E/VLC/JNI/VLCObject: FindClass(org/videolan/libvlc/interfaces/IMedia$Track) failed
2022-07-26 17:59:13.258 17311-17311/? E/VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.mtdataje.au.dvr_co_driver-58r3iTZNZoPsXtLhK1M3hg==/lib/arm/libvlcjni.so"
2022-07-26 17:59:13.408 3395-3430/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{db2cebc u0 com.mtdataje.au.dvr_co_driver/com.mtdataje.au.dvr_co_driver.MainActivity}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:4013)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5574)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2022-07-26 17:59:13.411 9922-12266/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2022-07-26 17:59:13.412 9922-12266/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2022-07-26 17:59:13.414 9922-12266/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2022-07-26 17:59:13.436 10083-10083/? E/ComponentHelper: getVersionCode:android.content.pm.PackageManager$NameNotFoundException: com.samsung.android.themestore
2022-07-26 17:59:13.465 10083-11225/? E/IconLoader: Unexpected null component name or activity info: ComponentInfo{com.android.vending/com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity}, null
```

Everything is working fine if I run it as a standard debug process. Here is my Flutter Doctor

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale en-AU)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\dabra\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32510.428
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\dabra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • SM T390 (mobile)  • 5200f9264aac95a1 • android-arm    • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 103.0.1264.62

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

Any ideas? I have been stuck on this all day :(.

**Comment by EBoehmecke** [comment]
Disabling obfuscation and resource shrinking fixed it for me.
Try to add/change the following in your android/app/build.gradle:

buildTypes {
        release {
            shrinkResources false
            minifyEnabled false
            useProguard false
            signingConfig signingConfigs.debug
        }
    }

**Comment by This-Is-Not-Brad** [comment]
Ended up working out the issues. When I was building the binaries the cross-compiled ones had this error. 

When I built the apk's with

```
flutter build apk --split-per-abi
```

And installed the correct apk for the architecture and it now is working....
