### ISSUE TITLE
Exception on updating vlc playing url

### ISSUE THREAD

**Issue by alr2413** [solid-software/flutter_vlc_player#85]
Hi, 

First, special thanks for providing this package. My problem is that whenever I'm switching the streaming url the following exception raised:

`
W/System  ( 8676): A resource failed to call release. 
E/System  ( 8676): Uncaught exception thrown by finalizer
E/System  ( 8676): java.lang.AssertionError: VLCObject (org.videolan.libvlc.Media) finalized but not natively released (7 refs)
E/System  ( 8676): 	at org.videolan.libvlc.VLCObject.finalize(VLCObject.java:109)
E/System  ( 8676): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
E/System  ( 8676): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
E/System  ( 8676): 	at java.lang.Daemons$Daemon.run(Daemons.java:137)
E/System  ( 8676): 	at java.lang.Thread.run(Thread.java:919)
W/System  ( 8676): A resource failed to call release. 
`

From this, you can see that the previous instance of VLC Object still exists "finalized but not natively released (7 refs)". 
I have also a problem when i try to change the player fullscreen mode while playing the video. It cause the video goes blank while the audio is running.

If you have any idea about this issue, please share it.
Thanks.

**Comment by mitchross** [comment]
Can you reproduce this in the provided sample app in the repo?

**Comment by alr2413** [comment]
I'm not sure exactly, but when you change the video url this error may happen.
I also have found the following link about this issue that says we should also release the vlc on dispose method:
[Here is the link](https://github.com/jellyfin/jellyfin-androidtv/pull/131.)

**Comment by mitchross** [comment]
@alr2413  Looks like link is broke, can you repost the link?

**Comment by alr2413** [comment]
The link is working for me (you can also hover mouse on link to see the popup notification): https://github.com/jellyfin/jellyfin-androidtv/pull/131

If it's not working, here is the content of that post:

> Addresses the following error with libvlc objects not being released. I have not noticed if this actually causes any errors in the client though.
> 
> org.jellyfin.androidtv.debug E/System: java.lang.AssertionError: VLCObject (org.videolan.libvlc.LibVLC) finalized but not natively released (1 refs)
>         at org.videolan.libvlc.VLCObject.finalize(VLCObject.java:97)
>         at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
>         at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
>         at java.lang.Daemons$Daemon.run(Daemons.java:103)
>         at java.lang.Thread.run(Thread.java:764)
> 
> 

and here is the provided solution:

>         mVlcPlayer.stop();
>         mVlcPlayer.getVLCVout().detachViews();
>         mVlcPlayer.release();
>         mLibVLC.release();
>         mLibVLC = null;
>         mVlcPlayer = null;
>         mSurfaceView.setKeepScreenOn(false);
